### ISSUE TITLE
RuntimeError when training

### ISSUE THREAD

**Issue by NoviceCrom** [zjukg/KoPA#12]
![image](https://github.com/zjukg/KoPA/assets/48437212/fc9effbd-2139-467d-9164-d86dabd5dae1)

**Comment by Zhang-Each** [comment]
This can be caused by a python library version mismatch. Our environment setting is python==3.9, transformers==4.28.0, peft==0.3.0

**Comment by Yclock** [comment]
> ![image](https://private-user-images.githubusercontent.com/48437212/283827876-fc9effbd-2139-467d-9164-d86dabd5dae1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTM3ODMsIm5iZiI6MTcxOTIxMzQ4MywicGF0aCI6Ii80ODQzNzIxMi8yODM4Mjc4NzYtZmM5ZWZmYmQtMjEzOS00NjdkLTkxNjQtZDg2ZGFiZDVkYWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA3MTgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYjgwNGUzNmNlOWZmZWE5MTFkODdlMzY5OWExMjA5ZDM2NTQzZGI3ODMxNjIwZGNkOGFhZGJhZDQ0MzI3OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JaHisrIrhL6EvESdVZC341wHjLOTYSZsdlRYl2RyAoE)

Hey, How did you solve this problem? Thank you.
