### ISSUE TITLE
总是出现这个问题KeyError: 'ent_re_embeddings.weight'

### ISSUE THREAD

**Issue by haitaoneu** [zjukg/KoPA#16]
你的工作非常出色，我也在学习您的工作，在复现过程中出现了一些问题，麻烦您帮忙看看，谢谢
base_model: str = "tatsu-lab/alpaca-7b-wdiff" 或者base_model: str = "huggyllama/llama-7b"  两个预训练模型我都尝试过，都会出现加载预训练知识图嵌入（KGE）模型时，试图通过键值 'ent_re_embeddings.weight' 访问字典 kge_model 的条目时发生了 KeyError。
Training Alpaca-LoRA model with params:
base_model: /root/autodl-fs/alpaca-7b-wdiff
data_path: /root/KoPA/data/UMLS-train.json
output_dir: ./lora-alpaca
batch_size: 16
micro_batch_size: 16
num_epochs: 2
learning_rate: 0.0003
cutoff_len: 512
val_set_size: 0
lora_r: 16
num_prefix: 1
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: ['q_proj', 'v_proj']
train_on_inputs: True
add_eos_token: False
group_by_length: False
wandb_project: 
wandb_run_name: 
wandb_watch: 
wandb_log_model: 
resume_from_checkpoint: False
prompt template: alpaca
kge model: /root/KoPA/data/UMLS-rotate.pth

Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████| 6/6 [00:06<00:00,  1.14s/it]
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Traceback (most recent call last):
  File "finetune_kopa.py", line 281, in <module>
    fire.Fire(train)
  File "/root/miniconda3/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "finetune_kopa.py", line 181, in train
    slama_model = KoPAWithAdapter(model, num_prefix, kge_model=kge_model)
  File "/root/KoPA/kopa.py", line 70, in __init__
    ent_embs, rel_embs = load_pretrain_kge(kge_model)
  File "/root/KoPA/process_kge.py", line 6, in load_pretrain_kge
    return load_complex_model(path)
  File "/root/KoPA/process_kge.py", line 24, in load_complex_model
    ent_embs1 = torch.tensor(kge_model["ent_re_embeddings.weight"]).cpu()
KeyError: 'ent_re_embeddings.weight'
请帮忙看看哪里出现了问题，谢谢

**Comment by Zhang-Each** [comment]
你好，经过我的排查，使用我们提供的UMLS-rotate.pth预训练embedding时，上面这段代码不会出现你提到的keyError的问题。key_model中的key包括odict_keys(['zero_const', 'pi_const', 'ent_embedding_range', 'rel_embedding_range', 'margin', 'ent_embeddings.weight', 'rel_embeddings.weight'])
