### ISSUE TITLE
 the method are in doubt

### ISSUE THREAD

**Issue by Log4J-Ops** [zjukg/KoPA#22]
Thank you for your method. I repeated this method and used it for entity and relationship prediction. I found that the effect was not even as good as directly fine-tuning the model. What is the reason for this

**Comment by Zhang-Each** [comment]
Hello, how do you apply this method for entity/relation predition? As entity/relation prediction are ranking tasks, the design of the our prompt may not be suitable for the task and it's a valuable future direction.

**Comment by Log4J-Ops** [comment]
I just did a simple experiment, made simple changes to the prompts and masked the entities and the embedding ids in our input to make LLM predict. The effect was not even as good as fine-tuning without prefix, I can't figure out why this is😢

**Comment by Zhang-Each** [comment]
Well, I think how to employ KoPA for link prediction task should be further considered. We did not explore this problem in our paper yet. It will be a good topic for the future research
