### ISSUE TITLE
请问kge模型的训练过程。

### ISSUE THREAD

**Issue by estuday** [zjukg/KoPA#29]
您好，
论文中Structural Embedding Pre-training应该就是指代码中的kge_model吧，但是我没有找到如何训练嵌入模型，请问能否提供嵌入模型的训练代码？谢谢

**Comment by Zhang-Each** [comment]
你好，训练KGE模型的代码可以参考OpenKE[1], NeuralKG[2]等开源的知识图谱表示学习库来使用，我们在实验过程中是采用OpenKE来训练的，后续我们会补充这一部分的代码，你也可以直接使用数据集中已经预训练好的embedding进行实验。

[1] OpenKE: https://github.com/thunlp/OpenKE

[2] NeuralKG: https://github.com/zjukg/NeuralKG

**Comment by estuday** [comment]
> 你好，训练KGE模型的代码可以参考OpenKE[1], NeuralKG[2]等开源的知识图谱表示学习库来使用，我们在实验过程中是采用OpenKE来训练的，后续我们会补充这一部分的代码，你也可以直接使用数据集中已经预训练好的embedding进行实验。
> 
> [1] OpenKE: https://github.com/thunlp/OpenKE
> 
> [2] NeuralKG: https://github.com/zjukg/NeuralKG

十分感谢，我想问一下，代码中num_prefix是指图谱结构知识经过映射后，到文本空间的长度吗？是不是就像prefix tuning中prefix token的长度。

**Comment by Zhang-Each** [comment]
是的，可以这么理解
