### ISSUE TITLE
关于图谱embedding预训练模型的问题

### ISSUE THREAD

**Issue by lairongxuan** [zjukg/KoPA#31]
您好，在仓库开源的data中，有单独给出`.pth`的图预训练模型，请问是否可以把预训练的代码也共享？非常感谢。

**Comment by Zhang-Each** [comment]
你好，我们的预训练部分完全使用原始的开源项目OpenKE的代码，可以参考该项目进行不同的kg embedding预训练。

https://github.com/thunlp/OpenKE

**Comment by Zhang-Each** [comment]
`kg/`目录下的数据集已经处理成了OpenKE所需要的格式

**Comment by RongxuanLai** [comment]
好的，非常感谢。
