### ISSUE TITLE
Training-free Reasoning Approaches使用的prompt

### ISSUE THREAD

**Issue by vuvskp7** [zjukg/KoPA#32]
您好，请问可以提供一下trainging-free所使用的prompt吗
![image](https://github.com/zjukg/KoPA/assets/107998993/9897f410-e3eb-4f3e-90aa-fa090a8fa19a)

**Comment by Zhang-Each** [comment]
你好，这部分数据需要一段时间进行整理，我们会在后续更新相关内容。
