### ISSUE TITLE
关于模型输出问题

### ISSUE THREAD

**Issue by RongxuanLai** [zjukg/KoPA#33]
重新复现了您的工作，出现一个问题，请教一下：
按照paper中的实验设置，在A6000中训练了4个epoch，在推理阶段模型对每一个prompt的输出完全不在预计之内（如下图），最终得到的acc, p, r, f1分别为0.5, 0, 0, 0。请问这个问题可能出在哪？谢谢。
![2024-01-09_225650](https://github.com/zjukg/KoPA/assets/146648859/c0216b65-6f37-424d-bc61-a3138d41bf94)

**Comment by RongxuanLai** [comment]
采用的LLM与 https://github.com/zjukg/KoPA/issues/27#issuecomment-1870094773 一致

**Comment by Zhang-Each** [comment]
这种情况应该是推理阶段的LLM依然处于没有训练的状态，有可能是LoRA权重没有正确读取导致的，PEFT库在保存LoRA权重的时候有一个bug，有可能训练时的LoRA权重没有保存下来，你可以检查一下保存下来的LoRA权重的情况，具体解决方案是更换PEFT库的版本。
