### ISSUE TITLE
微调后的结果无法达到预期

### ISSUE THREAD

**Issue by greyovo** [zjukg/KoPA#34]
使用 `finetune_kopa.py` 脚本，使用 CoDeX 的数据集微调 `llama-7B` 后进行推理，得出的结果为：
```shell
acc p r f1
0.5043763676148797 0.5022038567493113 0.9972647702407003 0.6680102601685599
```
🤣 与KoPA的结果不一致，但与不微调的 Zero-shot 的结果出奇地一致，是我微调的设置有误么？

![image](https://github.com/zjukg/KoPA/assets/20888390/23494dfe-b6be-4d08-8f4c-34ee89bc1c15)

**微调参数**如下。其中 `batch_size` 由 12 调整为了 6（因为硬件资源有限）不知道有没有影响？

```shell
export WANDB_DISABLED=true
wandb offline
CUDA_VISIBLE_DEVICES=0 nohup python finetune_kopa.py \
    --base_model 'baffo32/decapoda-research-llama-7B-hf' \
    --data_path 'data/CoDeX-S-train.json' \
    --output_dir 'output-CoDeX' \
    --num_epochs 3 \
    --lora_r 64 \
    --learning_rate 3e-4 \
    --batch_size 6 \ 
    --micro_batch_size 6 \
    --num_prefix 1 \
    --kge_model 'data/CoDeX-S-rotate.pth' \
    --lora_target_modules='[q_proj,k_proj,v_proj,o_proj]' > log-CoDeX.log &
```

**推理的代码**基于 `inference_kopa.py` 修改：
```python
base_path = 'baffo32/decapoda-research-llama-7B-hf'
if __name__ == "__main__":
    cuda = "cuda:0"
    lora_weights = "output-CoDeX"
    test_data_path = "data/CoDeX-S-test.json"
    embedding_path = "{}/embeddings.pth".format(lora_weights)
    test_dataset = load_test_dataset(test_data_path)
    kg_embeddings = torch.load(embedding_path).to(cuda)
    tokenizer = LlamaTokenizer.from_pretrained(base_path)
    model = LlamaForCausalLM.from_pretrained(
        base_path,
        torch_dtype=torch.float16
    ).to(cuda)
    model = PeftModel.from_pretrained(
        model,
        lora_weights,
        torch_dtype=torch.float16,
    ).to(cuda)
```

**Comment by greyovo** [comment]
在 `output-CoDeX/checkpoint-80000/trainer_state.json` 中，最后几行内容是：

```json
....
    {
      "epoch": 2.92,
      "learning_rate": 8.248803594695632e-06,
      "loss": 0.0629,
      "step": 79990
    },
    {
      "epoch": 2.92,
      "learning_rate": 8.212272135020273e-06,
      "loss": 0.0627,
      "step": 80000
    }
  ],
  "max_steps": 82221,
  "num_train_epochs": 3,
  "total_flos": 0.0,
  "trial_name": null,
  "trial_params": null
}

```

**Comment by Zhang-Each** [comment]
这个有可能是peft版本的问题，你可以检查一下保存下来的lora权重里面是不是一个空文件。peft库和transformers版本不匹配的时候就会出现这种问题。

**Comment by Zhang-Each** [comment]
一般来说只要用数据训练过，模型肯定是不会出现zero-shot水平的性能的，很有可能就是peft库版本的问题，可以参考peft库的这个issue
https://github.com/huggingface/peft/issues/286

**Comment by greyovo** [comment]
谢谢，我去试一下。

**Comment by gaoIf** [comment]
麻烦问下，这个问题有解决吗。我查看了保存的lora权重确实是空的有问题
我的peft库是requirement.txt里的0.3.0
尝试了注释  
  # old_state_dict = model.state_dict
    # model.state_dict = (
    #     lambda self, *_, **__: get_peft_model_state_dict(
    #         self, old_state_dict()
    #     )
    # ).__get__(model, type(model))
但lora权重保存又太大
是需要升级0.4.0吗

**Comment by Zhang-Each** [comment]
> 麻烦问下，这个问题有解决吗。我查看了保存的lora权重确实是空的有问题 我的peft库是requirement.txt里的0.3.0 尝试了注释
> 
> # old_state_dict = model.state_dict
> ```
> # model.state_dict = (
> #     lambda self, *_, **__: get_peft_model_state_dict(
> #         self, old_state_dict()
> #     )
> # ).__get__(model, type(model))
> ```
> 
> 但lora权重保存又太大 是需要升级0.4.0吗

这个是peft库的问题，可以参考上面的链接里的方案尝试解决

**Comment by Frosty-Heart** [comment]
> 谢谢，我去试一下。

请问问题解决了吗，我删除那段代码之后没有adapter.bin了
