### ISSUE TITLE
您好，请问一下inductive设定是如何实现的

### ISSUE THREAD

**Issue by AriesWYu** [zjukg/KoPA#36]
llm和kg结合非常好的工作，有个问题：kopa使用了预训练的实体和关系embedding，那么是如何泛化到unseen实体的呢？具体实现可以解释一下吗

**Comment by Zhang-Each** [comment]
你好，这个实验里我们测定的是LLM对于未见过实体的embedding的泛化能力，在预先训练实体和关系的embedding的阶段是不inductive的，但是在LLM微调的过程中，我们会将一部分实体设定为unseen实体，将所有涉及到这个实体的训练数据从数据集中移除，然后在测试阶段用预训练的embedding+LLM没见过的实体去测试LLM能否实现对embedding的迁移能力

**Comment by AriesWYu** [comment]
非常感谢解答，是unseen embedding的泛化
