### ISSUE TITLE
关于inductive的一点疑问

### ISSUE THREAD

**Issue by serendipity800** [zjukg/KoPA#39]
请问：1. 本文使用的inductive setting中，有一些unseen entities，请问这些unseen entities是指没有在LLM训练过程中出现的entities，还是没有在TransE和LLM训练的过程中出现的entities？
2. 如果两个·知识图谱没有经过对齐，分别对两个模型进行训练得到了两组TransE / RotatE模型M1和M2，而LLM微调使用M1生成的embedding，请问不重新训练的情况下泛化到M2上？

**Comment by Zhang-Each** [comment]
1. 是指对于LLM而言unseen，对于KGE模型来说所有的实体和关系在预训练阶段都是可见的，主要测试的就是LLM能否将unseen实体的embedding进行迁移
2. 应该不能，目前该方法只能解决单个知识图谱上的三元组预测
