### ISSUE TITLE
结果为0.5，0.0，0.0，0.0

### ISSUE THREAD

**Issue by yhjiujiu** [zjukg/KoPA#41]
你好，我没有更改任何代码，并且采用的是standford alpaca。 但是在两个数据集上的结果是0.5，0.0，0.0，0.0. 并且查看了lora 权重并不是空文件，请问该如何解决这个问题？ 谢谢！！
<img width="916" alt="image" src="https://github.com/zjukg/KoPA/assets/39623606/52067172-857b-483e-8015-ff0900f4e800">
<img width="781" alt="image" src="https://github.com/zjukg/KoPA/assets/39623606/bb3ba165-2d93-4cc7-8ea1-ea3612cbba63">

**Comment by yhjiujiu** [comment]
> 这种情况有可能是checkpoint没有正确加载导致的

谢谢，我检查一下。而且我发现loss 一直没下降，始终为10.374. 如果用llama 7B模型，loss 会正常下降，并且推理结果也是在正常范围内。 这是什么原因导致的喃？？ 谢谢！

**Comment by Zhang-Each** [comment]
可能是alpaca模型版本导致的问题，我们实验使用的是原版的stanford alpaca

**Comment by liuyi-193** [comment]
> 这种情况有可能是checkpoint没有正确加载导致的

请问这里的checkpoint指的是微调产生的checkpoint-85000这种文件吗？如何判断checkpoint有没有正确加载？我还没有发现加载的代码，想请教一下，谢谢了。

**Comment by Zhang-Each** [comment]
> > 这种情况有可能是checkpoint没有正确加载导致的
> 
> 请问这里的checkpoint指的是微调产生的checkpoint-85000这种文件吗？如何判断checkpoint有没有正确加载？我还没有发现加载的代码，想请教一下，谢谢了。

你好，inference代码中会自动加载最后保存下来的checkpoint
