### ISSUE TITLE
训练相关问题

### ISSUE THREAD

**Issue by CHAOJICHENG5** [zjukg/KoPA#43]
你好我想请问一下，训练集中需要添加负样本吗，我看论文中Table2统计信息的CodeX-S-Train数据集中大小为32888，而我实际打开CoDeX-S-train.json数据集发现不仅包含正样本32,888，还包含负样本131,522。我想请问在训练的时候数据集中需要添加负样本吗？

**Comment by Zhang-Each** [comment]
是的，因为要让模型作出正负样本的判断，所以不能只有负样本，正样本可以通过随机替换头尾实体生成，这和传统的知识图谱表示模型训练是类似的
