### ISSUE TITLE
微调后推理的结果比论文中低很多FB15K-237N数据集+llama7B

### ISSUE THREAD

**Issue by TTYee** [zjukg/KoPA#44]
使用FB15K-237N数据集，`llama-7B`模型进行微调，推理结果为：
```
0.5651592511548748 0.5417185554171855 0.8460977388767323 0.6605295624940685
```
![image](https://github.com/zjukg/KoPA/assets/100339350/1a529e86-5302-4b05-940b-5777927be17a)

**微调参数**如下，在A6000上运行，batch_size=4：
```bash
export WANDB_DISABLED=true
wandb offline
CUDA_VISIBLE_DEVICES=0 nohup python finetune_kopa.py \
    --base_model 'baffo32/decapoda-research-llama-7B-hf' \
    --data_path 'data/FB15K-237N-train.json' \
    --output_dir 'output/llama_fb_2' \
    --num_epochs 3 \
    --lora_r 64 \
    --learning_rate 3e-4 \
    --batch_size 4 \
    --micro_batch_size 4 \
    --num_prefix 1 \
    --kge_model 'data/FB15K-237N-rotate.pth' \
    --lora_target_modules='[q_proj,k_proj,v_proj,o_proj]' > log_llama_fb2.txt &
```
微调后，loss大小为`'train_loss': 0.0794358075707171`
训练后的**lora权重文件**也不是空的，大小如下：
![image](https://github.com/zjukg/KoPA/assets/100339350/44e9e1c7-d133-4cf2-8dc6-ac45b98e4504)

**推理代码**：
```python
base_path = 'baffo32/decapoda-research-llama-7B-hf'
if __name__ == "__main__":
    cuda = "cuda:0"
    lora_weights = "output/llama_fb_2"
    test_data_path = "data/FB15K-237N-test.json"
```
请问可能是哪的问题导致了这样比较低的结果呢？

**Comment by Zhang-Each** [comment]
你好，具体原因尚不清楚，我们没有在llama-7b上用上述参数进行过实验，后续我们排查出问题之后会及时联系

**Comment by TTYee** [comment]
> 你好，具体原因尚不清楚，我们没有在llama-7b上用上述参数进行过实验，后续我们排查出问题之后会及时联系

好的谢谢。请问你们用的stanford alpaca模型是按照[https://github.com/tatsu-lab/stanford_alpaca](url)中的方法自己微调的吗？因为好像并没有看到官方发布的模型权重。

**Comment by Zhang-Each** [comment]
是的

**Comment by pipiyapi** [comment]
> 是的

请问可以分享一下stanford alpaca微调后的权重参数吗，感谢

**Comment by CalmaQi** [comment]
> > 你好，具体原因尚不清楚，我们没有在llama-7b上用上述参数进行过实验，后续我们排查出问题之后会及时联系
> 
> 好的谢谢。请问你们用的stanford alpaca模型是按照[https://github.com/tatsu-lab/stanford_alpaca](url)中的方法自己微调的吗？因为好像并没有看到官方发布的模型权重。

我也用的llama2-7b得到的结果差不多：

 `0.50036469730124 0.5002134319863404 0.8547289083394116 0.6310923615474375`
但是我的lora权重是400多B，所以感觉推理效果应该和没微调差不多？
请问您有没有再在llama2-7b试过

**Comment by Zhang-Each** [comment]
> > 是的
> 
> 请问可以分享一下stanford alpaca微调后的权重参数吗，感谢

你好，这个需要后续进一步整理

**Comment by Zhang-Each** [comment]
> > > 你好，具体原因尚不清楚，我们没有在llama-7b上用上述参数进行过实验，后续我们排查出问题之后会及时联系
> > 
> > 
> > 好的谢谢。请问你们用的stanford alpaca模型是按照[https://github.com/tatsu-lab/stanford_alpaca](url)中的方法自己微调的吗？因为好像并没有看到官方发布的模型权重。
> 
> 我也用的llama2-7b得到的结果差不多：
> 
> `0.50036469730124 0.5002134319863404 0.8547289083394116 0.6310923615474375` 但是我的lora权重是400多B，所以感觉推理效果应该和没微调差不多？ 请问您有没有再在llama2-7b试过

你好，这个情况是因为lora库的版本问题导致训练好的lora权重没保存下来，所以实际上模型在推理的时候的参数是训练前的版本

**Comment by Zhang-Each** [comment]
> > > > > 你好，具体原因尚不清楚，我们没有在llama-7b上用上述参数进行过实验，后续我们排查出问题之后会及时联系
> > > > 
> > > > 
> > > > 好的谢谢。请问你们用的stanford alpaca模型是按照[https://github.com/tatsu-lab/stanford_alpaca](url)中的方法自己微调的吗？因为好像并没有看到官方发布的模型权重。
> > > 
> > > 
> > > 我也用的llama2-7b得到的结果差不多：
> > > `0.50036469730124 0.5002134319863404 0.8547289083394116 0.6310923615474375` 但是我的lora权重是400多B，所以感觉推理效果应该和没微调差不多？ 请问您有没有再在llama2-7b试过
> > 
> > 
> > 你好，这个情况是因为lora库的版本问题导致训练好的lora权重没保存下来，所以实际上模型在推理的时候的参数是训练前的版本
> 
> 谢谢，请问我用的最新的peft库和transformer库，注释掉
> 
> ```
> old_state_dict = model.state_dict
>    model.state_dict = (
>        lambda self, *_, **__: get_peft_model_state_dict(
>            self, old_state_dict()
>        )
>    ).__get__(model, type(model))
> ```
> 
> 并且得到的是adaptor_model.safetensor文件是否ok

可以尝试一下

**Comment by CalmaQi** [comment]
> > > > > > 你好，具体原因尚不清楚，我们没有在llama-7b上用上述参数进行过实验，后续我们排查出问题之后会及时联系
> > > > > 
> > > > > 
> > > > > 好的谢谢。请问你们用的stanford alpaca模型是按照[https://github.com/tatsu-lab/stanford_alpaca](url)中的方法自己微调的吗？因为好像并没有看到官方发布的模型权重。
> > > > 
> > > > 
> > > > 我也用的llama2-7b得到的结果差不多：
> > > > `0.50036469730124 0.5002134319863404 0.8547289083394116 0.6310923615474375` 但是我的lora权重是400多B，所以感觉推理效果应该和没微调差不多？ 请问您有没有再在llama2-7b试过
> > > 
> > > 
> > > 你好，这个情况是因为lora库的版本问题导致训练好的lora权重没保存下来，所以实际上模型在推理的时候的参数是训练前的版本
> > 
> > 
> > 谢谢，请问我用的最新的peft库和transformer库，注释掉
> > ```
> > old_state_dict = model.state_dict
> >    model.state_dict = (
> >        lambda self, *_, **__: get_peft_model_state_dict(
> >            self, old_state_dict()
> >        )
> >    ).__get__(model, type(model))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 并且得到的是adaptor_model.safetensor文件是否ok
> 
> 可以尝试一下

谢谢

**Comment by Cameliasss** [comment]
请问楼主解决了吗？我训练之后也是差不多的数值，效果特别差

**Comment by CalmaQi** [comment]
> 请问楼主解决了吗？我训练之后也是差不多的数值，效果特别差

要不然使用peft0.3和transformer库对应；要不然就是注释掉old_state_dict = model.state_dict那一行

**Comment by xuanfeng666666** [comment]
我也是，使用CoDeX-S数据集跑出来的结果比论文中给出的结果差太多

![Image](https://github.com/user-attachments/assets/5c358e46-4a0f-4647-85fd-01d7d8a1839f)

**Comment by Zhang-Each** [comment]
> 我也是，使用CoDeX-S数据集跑出来的结果比论文中给出的结果差太多
> 
> ![Image](https://github.com/user-attachments/assets/5c358e46-4a0f-4647-85fd-01d7d8a1839f)

这种情况一般都是LoRA权重没有正确加载导致的

**Comment by xuanfeng666666** [comment]
> > 我也是，使用CoDeX-S数据集跑出来的结果比论文中给出的结果差太多
> > ![Image](https://github.com/user-attachments/assets/5c358e46-4a0f-4647-85fd-01d7d8a1839f)
> 
> 这种情况一般都是LoRA权重没有正确加载导致的

![Image](https://github.com/user-attachments/assets/265f45aa-c1ec-49c4-9188-d565eafb79c5)这是我训练结束后的结果，我该怎么排查问题所在呢，使得能够复现论文中的精度，感谢作者的耐心回复

**Comment by Zhang-Each** [comment]
> > > 我也是，使用CoDeX-S数据集跑出来的结果比论文中给出的结果差太多
> > > ![Image](https://github.com/user-attachments/assets/5c358e46-4a0f-4647-85fd-01d7d8a1839f)
> > 
> > 
> > 这种情况一般都是LoRA权重没有正确加载导致的
> 
> ![Image](https://github.com/user-attachments/assets/265f45aa-c1ec-49c4-9188-d565eafb79c5)这是我训练结束后的结果，我该怎么排查问题所在呢，使得能够复现论文中的精度，感谢作者的耐心回复

你好，分成训练和推理两个步骤来排查问题。
1. 训练的时候loss有没有下降，LoRA权重是否被正确保存下来，训练是否充分
2. 推理的时候LoRA权重是否成功加载
我观察到你给的截图里你只训练了1个epoch就结束了，一般要训练2-3个epoch才能达到最好的效果，然后就是你去看训练之后的权重有没有被保存和加载。
这个代码用的transformers和peft版本比较老了，当时标准库里存在很多细小的bug

**Comment by Zhang-Each** [comment]
> > > 我也是，使用CoDeX-S数据集跑出来的结果比论文中给出的结果差太多
> > > ![Image](https://github.com/user-attachments/assets/5c358e46-4a0f-4647-85fd-01d7d8a1839f)
> > 
> > 
> > 这种情况一般都是LoRA权重没有正确加载导致的
> 
> ![Image](https://github.com/user-attachments/assets/265f45aa-c1ec-49c4-9188-d565eafb79c5)这是我训练结束后的结果，我该怎么排查问题所在呢，使得能够复现论文中的精度，感谢作者的耐心回复

另外我看到你的另一个issue，说你因为设备原因无法支持fp16/bf16精度的训练，所以都改成了fp32，这个情况我之前也没遇到过，训练的时候的浮点数精度可能也对整体的效率和最终性能有很大影响。
