### ISSUE TITLE
 wandb: 未找到命令

### ISSUE THREAD

**Issue by wantsci** [zjukg/KoPA#45]
您好，请问.sh脚本里面的wandb是否需要设置，因为我运行报错，网上看到说要填写wandb api之类的，还是说此代码只需要pip install wandb就行了
![image](https://github.com/zjukg/KoPA/assets/113997146/a5dd5f0b-d080-46fd-88d6-58c7dc6d0f77)

**Comment by Zhang-Each** [comment]
最好需要安装下wandb

**Comment by wantsci** [comment]
好的感谢，请问您安装的wandb版本是多少，我在考虑版本的问题？我装的是0.16.6的版本，但仍然会出现这个问题

**Comment by Zhang-Each** [comment]
我是0.14.0版本的
