### ISSUE TITLE
关于推理的问题

### ISSUE THREAD

**Issue by willer-lu** [zjukg/KoPA#46]
当执行推理步骤时有以下输出（基于llama-2-7B）

`A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.`

这种情况对结果是否有影响？如果有，应该修改代码的什么部分？
另：最终结果如下：
0.50027352297593 0.5001511944360447 0.9048140043763676 0.6442064264849074

**Comment by Zhang-Each** [comment]
你好，这个在推理阶段不影响模型正常使用。最终结果看起来像是没经过训练的模型随机猜测的结果，可能是checkpoint的加载不正确

**Comment by willer-lu** [comment]
> 你好，这个在推理阶段不影响模型正常使用。最终结果看起来像是没经过训练的模型随机猜测的结果，可能是checkpoint的加载不正确
