### ISSUE TITLE
ValueError: Attempting to unscale FP16 gradients.

### ISSUE THREAD

**Issue by Lylovewhy** [zjukg/KoPA#48]
在运行python finetune_kopa.py时出现以下问题：
![image](https://github.com/zjukg/KoPA/assets/130729758/a874056e-d1b5-4e92-8ad2-e200aabf7747)

**Comment by Lylovewhy** [comment]
是不是我的peft和transformer的版本问题呀

**Comment by Lylovewhy** [comment]
最初的时候出现了这个错误：
![image](https://github.com/zjukg/KoPA/assets/130729758/54506a80-dc14-47dd-aa34-656d354bfe3a)
我就把from peft import 中的prepare_model_for_int8_training改成了prepare_model_for_kbit_training

**Comment by Zhang-Each** [comment]
你好，这可能有两方面原因，一是transformers库和peft的版本问题，二可能是gpu型号以及cuda版本的问题

**Comment by Lylovewhy** [comment]
> 你好，这可能有两方面原因，一是transformers库和peft的版本问题，二可能是gpu型号以及cuda版本的问题

你好 我发现我直接Pip install peft会出现以下问题：
![Uploading image.png…]()
请问你当时用的peft是哪个版本呢 0.3.0那个好像找不到┭┮﹏┭┮

**Comment by Lylovewhy** [comment]
> 你好，这可能有两方面原因，一是transformers库和peft的版本问题，二可能是gpu型号以及cuda版本的问题

你好 我发现我直接Pip install peft会出现以下问题：
![0d121746e8cf5ff8cfe6e157b5ea004](https://github.com/zjukg/KoPA/assets/130729758/5582eb71-547a-4cdb-9aec-a6fe5460f82f)
应该是我的peft版本的问题 我的peft版本是0.11.1 请问您当时用的是哪个版本呀
