### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization

### ISSUE THREAD

**Issue by Air2024** [zjukg/KoPA#49]
在利用finetune_kopa.py进行微调时并没有报错，但在inference_kopa.py加载lora微调参数后报错。我微调的模型是：alpaca-7b
报错信息：
![1717740711082](https://github.com/zjukg/KoPA/assets/95061536/671c9a88-d97f-4ec6-a417-7229f37e1fec)
微调参数：
![1717740787487](https://github.com/zjukg/KoPA/assets/95061536/d5b1bbeb-9b20-4765-baaf-539ba07102c7)
![1717740811598](https://github.com/zjukg/KoPA/assets/95061536/7dc569b5-76a1-4143-b4a1-ad8712fc5fcd)

**Comment by Zhang-Each** [comment]
你好，我们也没有遇到过此类问题，这应该跟safetensors这种保存方式有关，具体的我也不是很清楚，因为我没用过这种方式存储模型文件

**Comment by Air2024** [comment]
还有就是即使加载了其他格式的模型，加载embdding.pth预训练模型以后，进行嵌入发现输出的结果是空，加载路径没有错误。
![Image_1717841911947](https://github.com/zjukg/KoPA/assets/95061536/5d28fd0d-954b-49b8-a99a-c2ec8b6ebad7)
![Image_1717841915346](https://github.com/zjukg/KoPA/assets/95061536/bbb19906-97db-4d2e-909b-261d62240a71)

**Comment by Zhang-Each** [comment]
你是否进行过训练？可能是训练的时候不稳定导致出现了NAN

**Comment by Air2024** [comment]
已经微调过了，我在使用standar-alpaca模型后问题得到了解决，非常感谢作者，祝你的论文早日被录用，另外端午安康哦，记得吃粽子。
