### ISSUE TITLE
ImportError: cannot import name 'get_env_vars' from 'triton._C.libtriton.triton' (unknown location)

### ISSUE THREAD

**Issue by Yclock** [zjukg/KoPA#51]
在运行python finetune_kopa.py时报错如下：
Traceback (most recent call last):
  File "/home/leike/yyc/KoPA/finetune_kopa.py", line 17, in <module>
    from peft import (
  File "/home/leike/miniconda3/envs/kopa/lib/python3.9/site-packages/peft/__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "/home/leike/miniconda3/envs/kopa/lib/python3.9/site-packages/peft/mapping.py", line 16, in <module>
    from .peft_model import (
  File "/home/leike/miniconda3/envs/kopa/lib/python3.9/site-packages/peft/peft_model.py", line 31, in <module>
    from .tuners import (
  File "/home/leike/miniconda3/envs/kopa/lib/python3.9/site-packages/peft/tuners/__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "/home/leike/miniconda3/envs/kopa/lib/python3.9/site-packages/peft/tuners/lora.py", line 40, in <module>
    import bitsandbytes as bnb
  File "/home/leike/miniconda3/envs/kopa/lib/python3.9/site-packages/bitsandbytes/__init__.py", line 15, in <module>
    from .nn import modules
  File "/home/leike/miniconda3/envs/kopa/lib/python3.9/site-packages/bitsandbytes/nn/__init__.py", line 17, in <module>
    from .triton_based_modules import (
  File "/home/leike/miniconda3/envs/kopa/lib/python3.9/site-packages/bitsandbytes/nn/triton_based_modules.py", line 6, in <module>
    from bitsandbytes.triton.dequantize_rowwise import dequantize_rowwise
  File "/home/leike/miniconda3/envs/kopa/lib/python3.9/site-packages/bitsandbytes/triton/dequantize_rowwise.py", line 12, in <module>
    import triton
  File "/home/leike/miniconda3/envs/kopa/lib/python3.9/site-packages/triton/__init__.py", line 20, in <module>
    from .runtime import (
  File "/home/leike/miniconda3/envs/kopa/lib/python3.9/site-packages/triton/runtime/__init__.py", line 1, in <module>
    from .autotuner import Config, Heuristics, autotune, heuristics
  File "/home/leike/miniconda3/envs/kopa/lib/python3.9/site-packages/triton/runtime/autotuner.py", line 7, in <module>
    from ..compiler import OutOfResources
  File "/home/leike/miniconda3/envs/kopa/lib/python3.9/site-packages/triton/compiler/__init__.py", line 1, in <module>
    from .compiler import (CompiledKernel, ASTSource, compile, AttrsDescriptor)
  File "/home/leike/miniconda3/envs/kopa/lib/python3.9/site-packages/triton/compiler/compiler.py", line 6, in <module>
    from .._C.libtriton.triton import (get_env_vars, ir)
ImportError: cannot import name 'get_env_vars' from 'triton._C.libtriton.triton' (unknown location)

版本如下：
accelerate                0.31.0
aiofiles                  23.2.1
aiohttp                   3.9.5
aiosignal                 1.3.1
altair                    5.3.0
annotated-types           0.7.0
anyio                     4.4.0
appdirs                   1.4.4
asttokens                 2.4.1
async-timeout             4.0.3
attrs                     23.2.0
bitsandbytes              0.43.1
black                     24.4.2
Brotli                    1.0.9
certifi                   2024.6.2
charset-normalizer        3.1.0
click                     8.1.7
cmake                     3.29.5.1
contourpy                 1.2.1
cycler                    0.12.1
datasets                  2.19.2
decorator                 5.1.1
dill                      0.3.8
dnspython                 2.6.1
email_validator           2.1.1
exceptiongroup            1.2.1
executing                 2.0.1
fastapi                   0.111.0
fastapi-cli               0.0.4
ffmpy                     0.3.2
filelock                  3.13.1
fire                      0.6.0
fonttools                 4.53.0
frozenlist                1.4.1
fsspec                    2024.3.1
gmpy2                     2.1.2
gradio                    4.36.1
gradio_client             1.0.1
h11                       0.14.0
hf_transfer               0.1.6
httpcore                  1.0.5
httptools                 0.6.1
httpx                     0.27.0
huggingface-hub           0.23.3
idna                      3.7
importlib_resources       6.4.0
ipython                   8.18.1
jedi                      0.19.1
Jinja2                    3.1.4
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
lit                       18.1.7
loralib                   0.1.2
markdown-it-py            3.0.0
MarkupSafe                2.1.3
matplotlib                3.9.0
matplotlib-inline         0.1.7
mdurl                     0.1.2
mkl-fft                   1.3.8
mkl-random                1.2.4
mkl-service               2.4.0
mpmath                    1.3.0
multidict                 6.0.5
multiprocess              0.70.16
mypy-extensions           1.0.0
networkx                  3.2.1
numpy                     1.26.4
nvidia-cublas-cu11        11.10.3.66
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu11    11.7.101
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu11    11.7.99
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu11  11.7.99
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu11         8.5.0.96
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu11         10.9.0.58
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu11        10.2.10.91
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu11      11.4.0.1
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu11      11.7.4.91
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu11          2.14.3
nvidia-nccl-cu12          2.20.5
nvidia-nvjitlink-cu12     12.5.40
nvidia-nvtx-cu11          11.7.91
nvidia-nvtx-cu12          12.1.105
orjson                    3.10.4
packaging                 24.1
pandas                    2.2.2
parso                     0.8.4
pathspec                  0.12.1
peft                      0.3.0
pexpect                   4.9.0
pillow                    10.3.0
pip                       24.0
platformdirs              4.2.2
prompt_toolkit            3.0.47
psutil                    5.9.8
ptyprocess                0.7.0
pure-eval                 0.2.2
pyarrow                   16.1.0
pyarrow-hotfix            0.6
pydantic                  2.7.3
pydantic_core             2.18.4
pydub                     0.25.1
Pygments                  2.18.0
pyparsing                 3.1.2
PySocks                   1.7.1
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-multipart          0.0.9
pytz                      2024.1
PyYAML                    6.0.1
referencing               0.35.1
regex                     2024.5.15
requests                  2.32.2
rich                      13.7.1
rpds-py                   0.18.1
ruff                      0.4.8
safetensors               0.4.3
semantic-version          2.10.0
sentencepiece             0.2.0
setuptools                69.5.1
shellingham               1.5.4
six                       1.16.0
sniffio                   1.3.1
stack-data                0.6.3
starlette                 0.37.2
sympy                     1.12.1
termcolor                 2.4.0
tokenize-rt               5.2.0
tokenizers                0.13.3
tomli                     2.0.1
tomlkit                   0.12.0
toolz                     0.12.1
torch                     2.0.0+cu118
torchaudio                2.0.1+cu118
torchvision               0.15.1+cu118
tqdm                      4.66.4
traitlets                 5.14.3
transformers              4.28.0
triton                    2.0.0
typer                     0.12.3
typing_extensions         4.11.0
tzdata                    2024.1
ujson                     5.10.0
urllib3                   2.2.1
uvicorn                   0.30.1
uvloop                    0.19.0
watchfiles                0.22.0
wcwidth                   0.2.13
websockets                11.0.3
wheel                     0.43.0
xxhash                    3.4.1
yarl                      1.9.4
zipp                      3.19.2
请问您知道是什么问题吗？

**Comment by Zhang-Each** [comment]
你好，应该还是python环境配置的问题。有一些库的版本不匹配，不过具体我也不太清楚，我们在实验中没碰到过过此类问题。

**Comment by Yclock** [comment]
> 你好，应该还是python环境配置的问题。有一些库的版本不匹配，不过具体我也不太清楚，我们在实验中没碰到过过此类问题。

好的感谢

**Comment by Yclock** [comment]
> 你好，应该还是python环境配置的问题。有一些库的版本不匹配，不过具体我也不太清楚，我们在实验中没碰到过过此类问题。

对了，请问一共需要多大的显存？我看issues里提到分布式训练会有问题，单卡我最多只有24G。

**Comment by Zhang-Each** [comment]
> > 你好，应该还是python环境配置的问题。有一些库的版本不匹配，不过具体我也不太清楚，我们在实验中没碰到过过此类问题。
> 
> 对了，请问一共需要多大的显存？我看issues里提到分布式训练会有问题，单卡我最多只有24G。

可能需要40G以上

**Comment by Yclock** [comment]
> > > 你好，应该还是python环境配置的问题。有一些库的版本不匹配，不过具体我也不太清楚，我们在实验中没碰到过过此类问题。
> > 
> > 
> > 对了，请问一共需要多大的显存？我看issues里提到分布式训练会有问题，单卡我最多只有24G。
> 
> 可能需要40G以上

好的，谢谢解答

**Comment by AlexMa0** [comment]
你好，请问你解决这个问题了吗，我也遇到了相同的问题mportError: cannot import name 'get_env_vars' from 'triton._C.libtriton.triton' (unknown location)

**Comment by Yclock** [comment]
> 你好，请问你解决这个问题了吗，我也遇到了相同的问题mportError: cannot import name 'get_env_vars' from 'triton._C.libtriton.triton' (unknown location)

我解决了，我重新配置了环境，建议是先按照readme配置好pytorch、transformers、peft然后把requirements里这几块删除，再pip install -r requirements.txt，按照这个流程我是可以了。
