### ISSUE TITLE
关于论文表1中的P、R、F1指标的计算。

### ISSUE THREAD

**Issue by zhl98** [zjukg/KoPA#52]
非常感谢你们关于LLM4KG的工作。
我看表1表示的是三元组分类任务，true or false，请问这个ACC指标我能理解，其他三个指标是怎么计算的，好像并没有召回。

**Comment by Zhang-Each** [comment]
测试集里正负样本都有，把这个任务看成是常规的二分类即可。

**Comment by zhl98** [comment]
好的，理解了，谢谢您

**Comment by zhl98** [comment]
关于消融实验中的Random，是指在训练过程中输入到adapter的实体和关系embedding是随机初始化的么？

**Comment by Zhang-Each** [comment]
是的
