### ISSUE TITLE
data processing

### ISSUE THREAD

**Issue by 920Galaxy** [zjukg/KoPA#53]
Hi, could you provide the code for processing the data?

**Comment by 920Galaxy** [comment]
About the code for generating ’FB15K-237N-train.json‘

**Comment by Zhang-Each** [comment]
The data pre-processing code is hard to find now. But I think it is not difficult to pre-process your own datasets into the same format as the provided datasets. We are trying to recover the data pre-processing scripts.

**Comment by Single-specical** [comment]
> The data pre-processing code is hard to find now. But I think it is not difficult to pre-process your own datasets into the same format as the provided datasets. We are trying to recover the data pre-processing scripts.

Ok, thanks for your answer, I'll try to write it out
