### ISSUE TITLE
Question about the test

### ISSUE THREAD

**Issue by ysh000112** [zjukg/KoPA#54]
Hello! I would like to ask about testing, I would like to ask if testing is done on test+ and test- at the same time or just on test+?

**Comment by Zhang-Each** [comment]
What do you mean about test + or test -? Positive samples and negative samples?

**Comment by ysh000112** [comment]
I mean, does the model use test+ when performing the test, or is test+ and test- mixed together as a whole test

**Comment by Zhang-Each** [comment]
Both

**Comment by ysh000112** [comment]
ok，thanks！
