### ISSUE TITLE
能否提供数据预处理和KGE预训练的程序？

### ISSUE THREAD

**Issue by ldp2211479** [zjukg/KoPA#58]
请问能否提供数据预处理和KGE预训练的代码？如果我想测试其他KG，应该如何做？

**Comment by Zhang-Each** [comment]
你好，这个只需要自己将对应数据集处理成样例数据相同的格式就可以

**Comment by ldp2211479** [comment]
谢谢回复。请问能否提供KGE的代码？如果我的KG过大，请问是否需要采样？

**Comment by Zhang-Each** [comment]
> 谢谢回复。请问能否提供KGE的代码？如果我的KG过大，请问是否需要采样？

我们的KG Embedding都是用OpenKE直接训练的，不怎么需要改动，你可以直接找到OpenKE项目的源代码运行KGE训练这部分内容。

**Comment by ldp2211479** [comment]
好的谢谢！
