### ISSUE TITLE
关于微调结果

### ISSUE THREAD

**Issue by Tsu7kino** [zjukg/KoPA#59]
您好！
请问我使用huggyllama/llama-7b在一张A100上进行CoDex-S数据集上复现，并且确保环境配置与readme.md中的相同，复现的结果为0.8096280087527352  0.7873096446700507  0.8484682713347921  0.8167456556082149，召回率R明显低于论文中的91.41，可以请问下这可能是什么原因导致的吗，或者您有其他建议吗？
期待您的答复！谢谢

**Comment by Zhang-Each** [comment]
你好，precision和recall有波动属于正常现象。我们论文中主要关注accuracy和F1这两个指标

**Comment by Frosty-Heart** [comment]
> 您好！ 请问我使用huggyllama/llama-7b在一张A100上进行CoDex-S数据集上复现，并且确保环境配置与readme.md中的相同，复现的结果为0.8096280087527352 0.7873096446700507 0.8484682713347921 0.8167456556082149，召回率R明显低于论文中的91.41，可以请问下这可能是什么原因导致的吗，或者您有其他建议吗？ 期待您的答复！谢谢

您好，请问一下您的参数配置是什么样的呢，想请问一下，我复现的结果没有那么好谢谢了

**Comment by Zhangxiaoyi688** [comment]
您好，请问一下您的环境配置是什么样的，我这边微调的结果和Zero-shot结果差不多
