### ISSUE TITLE
复现代码时出现 can't load tokenizer

### ISSUE THREAD

**Issue by Guo-Chenxu** [zjukg/KoPA#7]
作者好, 我想问一下你们用的是 [tloen/alpaca-lora-7b](https://huggingface.co/tloen/alpaca-lora-7b/tree/main) 这个模型吗, 我在运行代码的时候报了下面这个错误: 

![image](https://github.com/zjukg/KoPA/assets/90923304/f1ff5430-f136-4b48-a6c5-56fa15f1fc0a)

我的模型文件如下 (里面似乎确实没有 tokenizer 文件):

![image](https://github.com/zjukg/KoPA/assets/90923304/41dda389-12ca-4849-9d09-f6376160cd03)

我的运行指令如下:
```sh
CUDA_VISIBLE_DEVICES=0 nohup python finetune_kopa.py \
    --base_model '/home/guochenxu/pythonProjects/KoPA-main/models/lora_7b' \
    --data_path 'data/UMLS-train.json' \
    --output_dir '/home/guochenxu/pythonProjects/KoPA-main/out/finetune_kopa' \
    --num_epochs 3 \
    --lora_r 32 \
    --learning_rate 3e-4 \
    --batch_size 12 \
    --micro_batch_size 12 \
    --num_prefix 1 \
    --kge_model 'data/UMLS-rotate.pth' \
    --lora_target_modules='[q_proj,k_proj,v_proj,o_proj]' >log.txt &
```

所以想请教一下这些文件要从哪里去获取呢 ([alpaca-lora](https://github.com/tloen/alpaca-lora)那边也问了, 但是目前还没有回复)

另外如果可以的话, 我还想请问一下你们使用的 python/transformers/tokenizer/peft等相关库的具体版本, 因为之前运行的时候我似乎还报了一些其他的错误, 但是我换了几个版本的库以后就没再报过这些错了, 为了以防万一所以想再确认一下具体版本😂

感激不尽🙏

**Comment by Zhang-Each** [comment]
我们用的是Alpaca-7B，不是Alpaca-lora-7B，你发的这个仓库不包含tokenizer的文件，所以代码无法load tokenizer，请你尝试使用别的版本的模型

**Comment by Guo-Chenxu** [comment]
> 我们用的是Alpaca-7B，不是Alpaca-lora-7B，你发的这个仓库不包含tokenizer的文件，所以代码无法load tokenizer，请你尝试使用别的版本的模型

好的, 感谢您的回答
